export const projectsDev = [
  {
    name: 'BlooBolt',
    href: 'bloobolt',
    imageSrc: '',
    imageAlt: '소프트웨어 개발자와 기획자, 디자이너들의 소통 스퀘어',
    date: 2023,
    skills: ['TypeScript', 'React', 'Next', 'Redux-Toolkit', 'TailwindCSS', 'Express', 'Sequelize', 'AWS'],
    description: '소프트웨어 개발자와 기획자, 디자이너들의 소통 스퀘어',
  },
  {
    name: 'BlooWays',
    href: 'blooways',
    imageSrc: '',
    imageAlt: '실시간 온라인 라이브 토크 메시지',
    date: 2023,
    skills: [
      'TypeScript',
      'React',
      'SWR',
      'TailwindCSS',
      'Styled-components',
      'Express',
      'Socket.io',
      'Sequelize',
      'AWS',
    ],
    description: '실시간 온라인 라이브 토크 메시지',
  },
  {
    name: 'Museum Union Gallery',
    href: 'mug',
    imageSrc: '',
    imageAlt: '전시 정보를 한 페이지에서 쉽게 확인할 수 있는 인터랙티브 웹 서비스',
    date: 2022,
    skills: ['JavaScript', 'JQuery', 'Express', 'Pug', 'SCSS', 'MongoDB'],
    description: '전시 정보를 한 페이지에서 쉽게 확인할 수 있는 인터랙티브 웹 서비스',
  },
  {
    name: 'Tira',
    href: 'tira',
    imageSrc: '',
    imageAlt: '티라미수 케이크 쇼핑몰 사이트',
    date: 2022,
    skills: ['JavaScript', 'JQuery', 'Express', 'Pug', 'SCSS'],
    description: '티라미수 케이크 쇼핑몰 사이트',
  },
];
